### PR TITLE
fix(massifs): add error message when bad polygon is loaded

### LINKED ISSUE #1217: [MASSIF - create] pb import polygone
**Describe the bug**
Le polygone suivant ne s'importe pas

[Bachsystem des Wienbaches.geojson.txt](https://github.com/user-attachments/files/25966089/Bachsystem.des.Wienbaches.geojson.txt)

### PR DESCRIPTION
**Pull request by Paul-AUB**
# Add error message when bad polygon is loaded

## 🤔 What

Display an error message to inform the user we can't load the topography

## 🤷‍♂️ Why

closes #1217 

## 🔍 How

Add 2 specific messages :
- Not enough points (not an area)
- Needle topography (too thin)

## 🧪 Testing

Added a test for needle topography detection in specific case of rivers.

## 📸 Previews

image

### CODE REVIEW

**Comment by ClemRz** [comment]
Please @Paul-AUB could you provide a sample file?

**Comment by Paul-AUB** [comment]
Sample file (rename without the .txt) : [Bachsystem.des.Wienbaches.geojson.txt](https://github.com/user-attachments/files/25980611/Bachsystem.des.Wienbaches.geojson.txt)
@ClemRz

File: packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap.jsx [hunk 1]
```diff
@@ -370,6 +374,23 @@ const PolygonMap = ({ onChange, data }) => {
       });
     });
 
+    if (newLayers.length === 0) {
+      if (skippedNeedle > 0) {
+        setImportError(
+          formatMessage({
+            id: 'The geometry could not be imported: all polygons are too thin or elongated (stream corridors, narrow buffers). Try increasing the simplification tolerance or use a different file.'
```
[the remark this answers is not in the document]
Comment (ClemRz) [reply packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap.jsx]: Actually, ignore my comment above. Your code is correct.

File: packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap.jsx [hunk 2]
```diff
@@ -370,6 +374,23 @@ const PolygonMap = ({ onChange, data }) => {
       });
     });
 
+    if (newLayers.length === 0) {
+      if (skippedNeedle > 0) {
```
Comment (ClemRz) [inline packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap.jsx:378]: The message won't show up if at least one polygon was not a "needle". See file attached.

[test-needle-and-valid.geojson.txt](https://github.com/user-attachments/files/25981201/test-needle-and-valid.geojson.txt)

Comment (ClemRz) [reply packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap.jsx:378]: Maybe that would rather be a warning in that case. The user could be oriented: by reducing the Simplification Tolerance those geometries might be included ... I'm not sure about the exact verbiage.

**Review by ClemRz — CHANGES_REQUESTED** [review]

**Review by ClemRz — APPROVED** [review]

**Comment by urien** [comment]
Pour moi cela fonctionne bien
